#!/bin/bash

current_version=7

version_file=`ls -al /root/ | grep .manager_version`
if [ "${version_file}" != "" ]; then
	old_version=`cat /root/.manager_version`
	if [ "${old_version}" != "" ] && [ ${old_version} -ge ${current_version} ]; then
		echo "the exist version of manager is newer than current, will do nothing"
		exit
	fi
fi

let start=${old_version}+1
for (( i = ${start}; i <= ${current_version}; i++ )); do
	execfile="./scripts/"${i}".sh"
	${execfile}
done
